language: node_js
node_js:
  - "10.8.0"

env:
 global:
   - GH_REF: github.com/395156224/resume.git

cache:
  yarn: true
  directories:
    - /node_modules/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

before_install:

install:

before_script:

script:
  - yarn build

after_script:
  # 导航到构建输出目录
  - cd docs
  - git init
  - git add -A
  - git commit -m 'deploy'

  # 推到你仓库的的 gh-page 分支
  #- git push --force git@github.com:395156224/resume.git master:gh-pages
  - git push --force --quiet  "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages